version: '3.9'

services:
  backend:
    build: ./backend
    container_name: machine_test_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/media
      - ./backend/db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=1
    restart: always

  frontend:
    build: ./frontend
    container_name: machine_test_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
